"""
Sieve generation for the webmail's rules, forwarding and vacation responder.

Part of 04-mailyte-web/02-PRD-webmail-standalone Phase 5, porting Laravel's
MailboxRuleCompiler and MailboxForwardingCompiler. The ManageSieve transport
they sit on already exists in utils/managesieve.py.

**Settings ride along in a marker comment rather than being recovered by
parsing Sieve.** The structure was in hand a moment before it was compiled;
writing a Sieve parser to get it back would be absurd, and a parser that
disagreed with the compiler would silently mangle someone's rules. Reading is
therefore exact for anything this compiler wrote, and anything it did not
write is reported as unmanaged rather than guessed at.

**Forwarding is `redirect :copy`, never a Postfix alias.** The alias route
duplicates delivery -- verified at the time as two copies of every message --
which is why this exists at all.
"""

import json
import logging
import re

from shared.ulid_utils import generate_ulid

logger = logging.getLogger(__name__)

FORWARDING_SCRIPT = "mailyte-forwarding"
FORWARDING_MARKER = "# mailyte-forwarding:"

RULES_SCRIPT = "mailyte-rules"
RULE_MARKER = "# mailyte-rule:"

VACATION_SCRIPT = "mailyte-vacation"
VACATION_MARKER = "# mailyte-vacation:"

# Matches the Laravel route's limit, so a mailbox that was within bounds stays
# within bounds.
MAX_FORWARD_ADDRESSES = 5
MAX_RULES = 50

_ADDRESS_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")
_HAS_SIEVE_RE = re.compile(r"^\s*(if|require|elsif|vacation)\b", re.MULTILINE)


def quote(value: str) -> str:
    """A Sieve quoted-string (RFC 5228 section 8.1).

    Backslash and double-quote are the only characters that need escaping.
    CR and LF are stripped rather than escaped: a quoted string cannot span
    lines, and a newline smuggled into an address is how someone would append
    their own commands to a script we generate.
    """
    cleaned = (value or "").replace("\r", "").replace("\n", "")
    return '"' + cleaned.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _marker_line(marker: str, payload: dict) -> str:
    return f"{marker} " + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def _read_markers(script: str | None, marker: str) -> list[dict]:
    if not script:
        return []
    found = []
    for line in script.splitlines():
        stripped = line.strip()
        if not stripped.startswith(marker):
            continue
        try:
            decoded = json.loads(stripped[len(marker) :].strip())
        except ValueError:
            # A corrupted marker means that one rule cannot be shown in the
            # builder. Losing the rest because of it would be worse.
            logger.warning("Unparseable %s marker skipped", marker)
            continue
        if isinstance(decoded, dict):
            found.append(decoded)
    return found


def _is_unmanaged(script: str | None, markers: list) -> bool:
    """True when a script exists, contains real Sieve, and none of it is ours.

    The webmail warns before replacing a script somebody wrote by hand or with
    another client -- overwriting a working filter without saying so is the
    kind of data loss nobody notices until mail stops arriving.
    """
    if not script:
        return False
    return not markers and bool(_HAS_SIEVE_RE.search(script))


# ---------------------------------------------------------------------------
# Forwarding
# ---------------------------------------------------------------------------


def clean_addresses(addresses, *, exclude: str | None = None) -> list[str]:
    out, seen = [], set()
    for raw in addresses or []:
        address = (raw or "").strip()
        if not address or not _ADDRESS_RE.match(address):
            continue
        lowered = address.lower()
        if lowered in seen:
            continue
        # Forwarding a mailbox to itself is a loop the mail server would then
        # have to break; refusing it here explains why instead.
        if exclude and lowered == exclude.lower():
            continue
        seen.add(lowered)
        out.append(address)
    return out


def compile_forwarding(settings: dict) -> str:
    addresses = settings.get("addresses") or []
    keep_copy = settings.get("keep_copy", True) is not False
    enabled = settings.get("enabled") is True and bool(addresses)

    marker = _marker_line(
        FORWARDING_MARKER,
        {"enabled": enabled, "addresses": addresses, "keep_copy": keep_copy},
    )

    if not enabled:
        # An inactive forward keeps its addresses so turning it back on is not
        # a retype. `keep;` is an explicit no-op delivery: a script that does
        # nothing at all is legal but reads like a mistake.
        return f"# Generated by Mailyte webmail -- forwarding is OFF.\n{marker}\nkeep;\n"

    # :copy = forward AND continue normal delivery. Without it, `redirect`
    # cancels the implicit keep and the message only goes onward -- which is
    # exactly the "do not keep a copy" case.
    requires = '["copy"]' if keep_copy else '["fileinto"]'
    body = "".join(
        f"    redirect :copy {quote(a)};\n" if keep_copy else f"    redirect {quote(a)};\n"
        for a in addresses
    )

    return (
        "# Generated by Mailyte webmail. Managed by the Forwarding settings --\n"
        "# edits here are replaced the next time forwarding is saved.\n"
        f"{marker}\n"
        f"require {requires};\n\n"
        "if true {\n"
        f"{body}"
        "}\n"
    )


def parse_forwarding(script: str | None) -> dict:
    markers = _read_markers(script, FORWARDING_MARKER)
    if markers:
        found = markers[0]
        return {
            "enabled": bool(found.get("enabled")),
            "addresses": list(found.get("addresses") or []),
            "keep_copy": found.get("keep_copy", True) is not False,
            "managed": True,
        }
    return {
        "enabled": False,
        "addresses": [],
        "keep_copy": True,
        "managed": not _is_unmanaged(script, markers),
    }


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------

_MATCH_TYPES = {"is": ":is", "matches": ":matches", "contains": ":contains"}

_CONDITION_HEADERS = {"from": "From", "to": "To", "cc": "Cc", "subject": "Subject"}


def _condition_test(condition: dict) -> str | None:
    field = str(condition.get("field") or "")
    match_type = _MATCH_TYPES.get(str(condition.get("operator") or "contains"), ":contains")
    value = quote(str(condition.get("value") or ""))

    if field in _CONDITION_HEADERS:
        return f'header {match_type} "{_CONDITION_HEADERS[field]}" {value}'
    if field == "body":
        return f"body :text {match_type} {value}"
    # An unknown field is dropped rather than guessed at -- emitting a test
    # for something the builder cannot show would filter mail invisibly.
    return None


def _action_statement(action: dict) -> str | None:
    kind = str(action.get("type") or "")
    value = str(action.get("value") or "").strip()
    if kind == "move":
        return f"fileinto {quote(value)};" if value else None
    if kind == "flag":
        return 'addflag "\\\\Flagged";'
    if kind == "mark_read":
        return 'addflag "\\\\Seen";'
    if kind == "forward":
        return f"redirect :copy {quote(value)};" if value else None
    if kind == "discard":
        return "discard;"
    return None


def _normalise_rule(rule: dict) -> dict:
    return {
        "id": rule.get("id") or generate_ulid(),
        "name": rule.get("name") or "Rule",
        "match": "any" if rule.get("match") == "any" else "all",
        "conditions": list(rule.get("conditions") or []),
        "actions": list(rule.get("actions") or []),
        "enabled": rule.get("enabled", True) is not False,
    }


def compile_rules(rules: list[dict]) -> str:
    # Extensions are derived from what the rules actually use, not from a
    # fixed list. Laravel's version hardcoded fileinto+imap4flags and added
    # `copy` for forwards but never `body` -- so any rule with a body
    # condition emitted `body :text` with no `require ["body"]`, which
    # Dovecot's Sieve compiler rejects outright. Deriving them cannot drift.
    requires = {"fileinto", "imap4flags"}
    chunks = []

    for raw in rules:
        rule = _normalise_rule(raw)
        marker = _marker_line(RULE_MARKER, rule)

        if not rule["enabled"]:
            # A disabled rule still round-trips: the definition survives so the
            # switch can be turned back on, but no Sieve is emitted.
            chunks.append(marker + "\n")
            continue

        tests = [t for t in (_condition_test(c) for c in rule["conditions"]) if t]
        statements = [s for s in (_action_statement(a) for a in rule["actions"]) if s]
        if not tests or not statements:
            # A rule with no usable test would match everything, and one with
            # no usable action would do nothing. Keep the definition, emit
            # nothing.
            chunks.append(marker + "\n")
            continue

        for condition in rule["conditions"]:
            if condition.get("field") == "body":
                requires.add("body")
        for action in rule["actions"]:
            if action.get("type") == "forward":
                requires.add("copy")

        operator = "anyof" if rule["match"] == "any" else "allof"
        test = tests[0] if len(tests) == 1 else f"{operator} (" + ", ".join(tests) + ")"
        block = f"if {test} {{\n" + "".join(f"    {s}\n" for s in statements) + "}\n"
        chunks.append(marker + "\n" + block + "\n")

    require_line = "require [" + ", ".join(f'"{e}"' for e in sorted(requires)) + "];"
    return (
        "# Generated by Mailyte webmail. Edited here, it stops round-tripping\n"
        "# back into the rule builder -- the builder recognises its own rules by\n"
        "# the marker comments below.\n"
        f"{require_line}\n\n" + "".join(chunks)
    )


def parse_rules(script: str | None) -> dict:
    markers = _read_markers(script, RULE_MARKER)
    return {
        "rules": [_normalise_rule(m) for m in markers],
        "managed": not _is_unmanaged(script, markers),
    }


# ---------------------------------------------------------------------------
# Vacation responder
# ---------------------------------------------------------------------------


def compile_vacation(settings: dict, own_address: str) -> str:
    enabled = settings.get("enabled") is True
    subject = (settings.get("subject") or "").strip()
    message = (settings.get("message") or "").strip()
    marker = _marker_line(
        VACATION_MARKER,
        {
            "enabled": enabled,
            "subject": subject,
            "message": message,
            "start_date": settings.get("start_date"),
            "end_date": settings.get("end_date"),
        },
    )

    if not enabled or not message:
        return (
            f"# Generated by Mailyte webmail -- the vacation responder is OFF.\n{marker}\nkeep;\n"
        )

    # :days 1 -- at most one auto-reply per sender per day. Without it a
    # correspondent in an active thread gets one for every message they send.
    # :addresses tells Sieve which addresses count as "me", so a message merely
    # Cc'd to a list this mailbox reads does not trigger a reply.
    args = [":days 1", f":addresses [{quote(own_address)}]"]
    if subject:
        args.append(f":subject {quote(subject)}")

    return (
        "# Generated by Mailyte webmail. Managed by the Vacation settings --\n"
        "# edits here are replaced the next time it is saved.\n"
        f"{marker}\n"
        'require ["vacation"];\n\n'
        "vacation " + " ".join(args) + " " + quote(message) + ";\n"
    )


def parse_vacation(script: str | None) -> dict:
    markers = _read_markers(script, VACATION_MARKER)
    if markers:
        found = markers[0]
        return {
            "enabled": bool(found.get("enabled")),
            "subject": found.get("subject") or None,
            "message": found.get("message") or None,
            "start_date": found.get("start_date"),
            "end_date": found.get("end_date"),
            "managed": True,
        }
    return {
        "enabled": False,
        "subject": None,
        "message": None,
        "start_date": None,
        "end_date": None,
        "managed": not _is_unmanaged(script, markers),
    }


# ---------------------------------------------------------------------------
# The active script
# ---------------------------------------------------------------------------

MAIN_SCRIPT = "mailyte-main"

# Every component script this module writes, in the order they must run.
COMPONENT_SCRIPTS = (RULES_SCRIPT, FORWARDING_SCRIPT, VACATION_SCRIPT)


def compile_main() -> str:
    """The one script that is actually active, including the others.

    **ManageSieve has a single active script, and this surface has three.**
    Saving each one active -- which is what the Laravel implementation did --
    means the last save wins and the other two silently stop running while the
    UI still shows them enabled. Forwarding would quietly stop the moment
    someone edited a rule. That is precisely the "control on screen that does
    not work" the PRD forbids.

    RFC 6609 `include` is the fix: one active script that pulls in each
    component. `:optional` because a mailbox that has never saved a rule has no
    rules script, and a missing include is a compile error that would take the
    whole filter chain down with it.

    Order is deliberate:

    * rules first -- filing and discarding decide whether the message survives
      at all;
    * forwarding second -- `redirect :copy` should still forward a message a
      rule has filed elsewhere;
    * vacation last -- an auto-reply to something already discarded as spam is
      the one outcome nobody wants.
    """
    includes = "".join(f'include :personal :optional "{name}";\n' for name in COMPONENT_SCRIPTS)
    return (
        "# Generated by Mailyte webmail. This is the ACTIVE script; it does\n"
        "# nothing itself except run the ones below, in order.\n"
        "#\n"
        "# Do not make a component script active directly -- Sieve allows only\n"
        "# one active script, so doing that silently switches the others off.\n"
        'require ["include"];\n\n'
        f"{includes}"
    )
