
[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:rspamd]
command=/usr/bin/rspamd -f -u _rspamd -g _rspamd
directory=/
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisor/rspamd.log
stderr_logfile=/var/log/supervisor/rspamd.log

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisor/rsyslog.log
stderr_logfile=/var/log/supervisor/rsyslog.log
