"""
Capability Manifest API

GET /api/v1/capabilities -- the whole CE/EE gating seam (ADR-001 "How gating
is implemented", console PRD SS11). The Mailyte Console fetches this once at
session start; an absent capability means the nav item is not rendered at
all, and the route redirects.

Unauthenticated by design: the console reads it before anyone has logged in,
so it cannot require a credential -- which is also why it must never return
tenant data, a hostname, or any other deployment detail.

THIS IS THE COMMUNITY EDITION MANIFEST. Unlike mailyte-email-server's copy,
`edition` is a constant, not read from MAILYTE_EDITION. This repo IS the
Community Edition; letting an env var flip it to "enterprise" would let a
misconfigured CE box advertise capabilities its own code does not implement.
Fail safe, not fail open.

!!! DO NOT EDIT !!!
Generated by scripts/build-ce.py from ce-manifest.yml in
mailyte-email-server. Editing this file here is how the capability list and
the route table drifted apart in the first place -- CE advertised webmail,
security and analytics with no code behind any of them. Change the manifest.
"""

from fastapi import APIRouter

router = APIRouter()

APP_VERSION = "1.0.0"
EDITION = "community"

# Every capability this edition ships. Generated from ce-manifest.yml's
# `capabilities.community`, and cross-checked at build time against
# `capability_owners` so a name here always has code behind it.
COMMUNITY_CAPABILITIES = [
    "domains",
    "mailboxes",
    "aliases",
    "dkim",
    "queue",
    "logs",
    "health",
    "overview",
    "directory",
    "mail_flow",
    "infrastructure",
    "governance",
    "docs",
    "settings",
    "webmail",
    "security",
    "analytics",
    "organizations",
]

# Documentation only -- never added to the response. ADR-001's gate is on
# scale and commercial capability, never on basic operability: CE gets a
# usable Mailcow-class panel, not a crippled demo.
ENTERPRISE_ONLY_CAPABILITIES = [
    "billing",
    "teams",
    "reports",
    "audit",
    "deliverability",
    "dkim_rotation",
    "migration",
    "rag",
    "whitelabel",
    "reseller",
    "priority_support",
    "dlp",
    "reputation",
    "compliance",
    "analytics_engagement",
    "analytics_reports",
]


@router.get(
    "/",
    summary="Get edition capability manifest",
    description="Returns the platform edition and the list of capabilities it ships. "
    "Unauthenticated by design -- the console and mailyte-web read this before login to "
    "decide which navigation entries and routes to render. Never exposes tenant data.",
)
async def get_capabilities():
    """Return this deployment's capability manifest.

    A constant, not a query: nothing here depends on the database, so the
    manifest still answers correctly while the rest of the stack is starting
    up -- which is exactly when a console is trying to decide what to render.
    """
    return {
        "edition": EDITION,
        "version": APP_VERSION,
        "capabilities": list(COMMUNITY_CAPABILITIES),
    }
