"""
Blocked senders -- /api/v1/mailbox/blocked-senders

Part of the mailbox-holder surface (routes/mailbox.py, 04-mailyte-web/
02-PRD-webmail-standalone). app.py mounts this router at the same
"/api/v1/mailbox" prefix; it is a separate module purely for file size, the
way smtp_credential_reports is split from smtp_credentials.

**"Blocked" means filed to Junk, not discarded.** A discard is silent and
irreversible: the one time the address was wrong, the mail is simply gone
and nothing anywhere says so. Junk is visible, reversible, and is where a
user already looks for mail that was kept from them. The folder is Dovecot's
``special_use = \\Junk`` mailbox, named ``Junk`` in mailer/dovecot/config/
dovecot.conf (``auto = create``, and ``fileinto :create`` covers a mailbox
that has never been opened over IMAP), and it is the same folder the global
spam rule files into -- one place, not two.

**One component script, included first.** The list compiles to its own
Sieve script (mailbox.BLOCKED_SENDERS_SCRIPT) that the active script
includes ahead of rules, forwarding and vacation. ``stop`` in an included
script ends the whole run (RFC 6609 section 3.2), so a blocked message is
neither forwarded on nor answered by the vacation responder. Like the other
components the list rides along in a marker comment, so reading it back is
exact rather than parsed out of Sieve; the round-trips of the other three
never touch this script, and this one never touches theirs.

**Matching is on the From header, whole address, case-insensitive** --
``address :is "from"`` with Sieve's default ``i;ascii-casemap`` comparator.
Envelope sender is deliberately not used: it is what a mailing list or a
forwarder rewrites, and a user blocking "that person" means the visible
sender.

**No handler here takes an account id from the path or the body.** The
session says which mailbox this is, exactly as in mailbox.py.
"""

import logging
import re

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from utils.auth import create_api_response
from utils.mailbox_auth import require_mailbox
from utils.sieve_compilers import _is_unmanaged, _marker_line, _read_markers, quote

from routes import mailbox as mailbox_routes

logger = logging.getLogger(__name__)

router = APIRouter()

# Named in mailbox.py because the active script it compiles has to include
# this component; the dependency runs one way (this module -> mailbox.py).
BLOCKED_SENDERS_SCRIPT = mailbox_routes.BLOCKED_SENDERS_SCRIPT
BLOCKED_SENDERS_MARKER = "# mailyte-blocked-senders:"

# Dovecot's \Junk special-use mailbox (dovecot.conf, namespace inbox).
JUNK_FOLDER = "Junk"

# Bounded so one list cannot approach sieve_max_script_size (1M) or make
# every delivery evaluate thousands of comparisons. 500 addresses is ~20KB.
MAX_BLOCKED_SENDERS = 500

# Dot-atom local part, dotted domain with at least one label separator. Tighter
# than sieve_compilers' address check on purpose: this value goes into a Sieve
# string list and a URL path segment, so no quotes, backslashes, brackets or
# whitespace of any kind.
_ADDRESS_RE = re.compile(
    r"^[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*"
    r"@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$"
)
_MAX_ADDRESS_LENGTH = 254


# ---------------------------------------------------------------------------
# Compilation
# ---------------------------------------------------------------------------


def normalise_address(raw: str | None) -> str | None:
    """Lower-cased address, or None if it is not one.

    Lower-casing makes add/remove idempotent and matches what the Sieve test
    does anyway (``:is`` is case-insensitive by default). Angle brackets are
    tolerated because that is how an address arrives when pasted from a
    header.
    """
    address = (raw or "").strip()
    if address.startswith("<") and address.endswith(">"):
        address = address[1:-1].strip()
    address = address.lower()
    if not address or len(address) > _MAX_ADDRESS_LENGTH or not _ADDRESS_RE.match(address):
        return None
    return address


def normalise_list(addresses) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for raw in addresses or []:
        address = normalise_address(raw if isinstance(raw, str) else None)
        if address and address not in seen:
            seen.add(address)
            out.append(address)
    return out


def compile_blocked_senders(addresses: list[str]) -> str:
    addresses = normalise_list(addresses)
    marker = _marker_line(BLOCKED_SENDERS_MARKER, {"addresses": addresses})
    header = (
        "# Generated by Mailyte webmail. Managed by the Blocked senders list --\n"
        "# edits here are replaced the next time a sender is blocked or unblocked.\n"
    )

    if not addresses:
        # Comments and the marker only. Deliberately NOT `keep;`: an explicit
        # keep is an action, and one that survives into the rules component
        # means a copy in INBOX alongside whatever a rule files elsewhere.
        # An empty script is legal Sieve and does exactly nothing.
        return f"{header}# No blocked senders.\n{marker}\n"

    listed = ", ".join(quote(address) for address in addresses)
    return (
        f"{header}"
        f"{marker}\n"
        'require ["fileinto", "mailbox"];\n\n'
        f'if address :is "from" [{listed}] {{\n'
        f"    fileinto :create {quote(JUNK_FOLDER)};\n"
        "    stop;\n"
        "}\n"
    )


def parse_blocked_senders(script: str | None) -> dict:
    markers = _read_markers(script, BLOCKED_SENDERS_MARKER)
    if markers:
        return {
            "addresses": normalise_list(markers[0].get("addresses") or []),
            "managed": True,
        }
    return {"addresses": [], "managed": not _is_unmanaged(script, markers)}


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


class BlockSenderRequest(BaseModel):
    address: str = Field(..., min_length=3, max_length=320)


def _current(email: str) -> dict:
    return parse_blocked_senders(mailbox_routes._read_script(email, BLOCKED_SENDERS_SCRIPT))


def _payload(parsed: dict) -> dict:
    return {**parsed, "folder": JUNK_FOLDER, "limit": MAX_BLOCKED_SENDERS}


def _invalid(message: str) -> HTTPException:
    return HTTPException(status_code=422, detail=create_api_response("error", message))


@router.get(
    "/blocked-senders",
    summary="Senders this mailbox has blocked",
    description=(
        "Mail from a blocked address is filed to the Junk folder at delivery, before "
        "any rule, forward or vacation reply runs. Nothing is discarded."
    ),
)
def blocked_senders_show(mailbox: dict = Depends(require_mailbox)):  # noqa: B008
    return create_api_response(
        "success", "Blocked senders retrieved successfully", _payload(_current(mailbox["email"]))
    )


@router.post(
    "/blocked-senders",
    summary="Block a sender",
    description=(
        "Adds one address. Matching is on the visible From address, whole address, "
        "case-insensitive. Blocking an address that is already blocked is not an error."
    ),
)
def blocked_senders_add(body: BlockSenderRequest, mailbox: dict = Depends(require_mailbox)):  # noqa: B008
    address = normalise_address(body.address)
    if not address:
        raise _invalid("Enter a valid email address to block")
    if address == (mailbox["email"] or "").strip().lower():
        # Own mail to self -- reminders, drafts sent onward -- would all land
        # in Junk, which is never what the click meant.
        raise _invalid("A mailbox cannot block its own address")

    current = _current(mailbox["email"])
    addresses = list(current["addresses"])
    if address in addresses:
        return create_api_response("success", "Sender is already blocked", _payload(current))
    if len(addresses) >= MAX_BLOCKED_SENDERS:
        raise _invalid(f"You can block at most {MAX_BLOCKED_SENDERS} senders")

    addresses.append(address)
    mailbox_routes._write_script(
        mailbox["email"], BLOCKED_SENDERS_SCRIPT, compile_blocked_senders(addresses)
    )
    return create_api_response(
        "success", "Sender blocked", _payload({"addresses": addresses, "managed": True})
    )


@router.delete(
    "/blocked-senders/{address}",
    summary="Unblock a sender",
    description=(
        "Removes one address. Unblocking an address that is not blocked is not an "
        "error. Mail already filed to Junk stays where it is."
    ),
)
def blocked_senders_remove(address: str, mailbox: dict = Depends(require_mailbox)):  # noqa: B008
    normalised = normalise_address(address)
    if not normalised:
        raise _invalid("That is not a valid email address")

    current = _current(mailbox["email"])
    if normalised not in current["addresses"]:
        return create_api_response("success", "Sender was not blocked", _payload(current))

    addresses = [a for a in current["addresses"] if a != normalised]
    mailbox_routes._write_script(
        mailbox["email"], BLOCKED_SENDERS_SCRIPT, compile_blocked_senders(addresses)
    )
    return create_api_response(
        "success", "Sender unblocked", _payload({"addresses": addresses, "managed": True})
    )
