-- =============================================================================
-- Migration 009: ULID Primary Keys
-- =============================================================================
-- Migrates ALL tables from INT AUTO_INCREMENT / VARCHAR(100) primary keys
-- to CHAR(26) ULID (Universally Unique Lexicographically Sortable Identifier).
--
-- ULIDs are 26-character strings generated in application code. They are:
--   - Globally unique (no collisions across distributed systems)
--   - Lexicographically sortable by creation time
--   - URL-safe (Crockford Base32)
--
-- Strategy:
--   1. Create a SQL helper function to generate ULID-like values for backfill
--   2. Drop ALL foreign key constraints
--   3. For INT/BIGINT PKs: add new_id CHAR(26), populate, drop old id, rename
--   4. For VARCHAR(100) PKs (organizations): ALTER COLUMN to CHAR(26)
--   5. Alter all foreign key columns to CHAR(26)
--   6. Re-add all foreign key constraints
--
-- WARNING: This is a destructive migration. Back up your database first.
-- Depends on: 008_missing_tables.sql
-- =============================================================================

-- =============================================================================
-- STEP 0: ULID generation helper for backfilling existing rows
-- =============================================================================
-- This generates a 26-char Crockford Base32 string. It is NOT a true ULID
-- (no embedded timestamp) but is sufficient for backfilling existing rows.
-- New rows will use real ULIDs generated by the Python application layer.

DELIMITER $$

DROP FUNCTION IF EXISTS generate_ulid_backfill$$

CREATE FUNCTION generate_ulid_backfill()
RETURNS CHAR(26) DETERMINISTIC
BEGIN
    DECLARE chars VARCHAR(32) DEFAULT '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    DECLARE result CHAR(26) DEFAULT '';
    DECLARE i INT DEFAULT 0;
    DECLARE rand_val BIGINT;

    -- Use a combination of timestamp and random for uniqueness
    SET rand_val = UNIX_TIMESTAMP(NOW(6)) * 1000000 + FLOOR(RAND() * 1000000);

    -- Generate 26 characters from Crockford Base32 alphabet
    WHILE i < 26 DO
        SET result = CONCAT(result, SUBSTRING(chars, FLOOR(RAND() * 32) + 1, 1));
        SET i = i + 1;
    END WHILE;

    RETURN result;
END$$

DELIMITER ;


-- =============================================================================
-- STEP 1: Drop ALL foreign key constraints
-- =============================================================================
-- We must drop every FK before altering column types.

-- domains -> organizations
ALTER TABLE domains DROP FOREIGN KEY fk_domains_org;

-- email_accounts -> domains, organizations
ALTER TABLE email_accounts DROP FOREIGN KEY fk_email_accounts_domain;
ALTER TABLE email_accounts DROP FOREIGN KEY fk_email_accounts_org;

-- aliases -> domains, organizations
ALTER TABLE aliases DROP FOREIGN KEY fk_aliases_domain;
ALTER TABLE aliases DROP FOREIGN KEY fk_aliases_org;

-- user_sessions -> email_accounts
ALTER TABLE user_sessions DROP FOREIGN KEY fk_sessions_email_account;

-- mail_queue -> organizations
ALTER TABLE mail_queue DROP FOREIGN KEY fk_mail_queue_org;

-- mail_logs -> organizations
ALTER TABLE mail_logs DROP FOREIGN KEY fk_mail_logs_org;

-- email_tracking -> organizations, domains
ALTER TABLE email_tracking DROP FOREIGN KEY fk_email_tracking_org;
ALTER TABLE email_tracking DROP FOREIGN KEY fk_email_tracking_domain;

-- tracking_statistics -> organizations, domains
ALTER TABLE tracking_statistics DROP FOREIGN KEY fk_tracking_stats_org;
ALTER TABLE tracking_statistics DROP FOREIGN KEY fk_tracking_stats_domain;

-- api_keys -> organizations
ALTER TABLE api_keys DROP FOREIGN KEY fk_api_keys_org;

-- webhook_urls -> organizations
ALTER TABLE webhook_urls DROP FOREIGN KEY fk_webhook_urls_org;

-- webhook_delivery_logs -> webhook_urls, organizations, domains
ALTER TABLE webhook_delivery_logs DROP FOREIGN KEY fk_webhook_delivery_url;
ALTER TABLE webhook_delivery_logs DROP FOREIGN KEY fk_webhook_delivery_org;
ALTER TABLE webhook_delivery_logs DROP FOREIGN KEY fk_webhook_delivery_domain;

-- alerts -> organizations, domains, email_accounts
ALTER TABLE alerts DROP FOREIGN KEY fk_alerts_org;
ALTER TABLE alerts DROP FOREIGN KEY fk_alerts_domain;
ALTER TABLE alerts DROP FOREIGN KEY fk_alerts_email_account;

-- usage_history -> organizations, domains, email_accounts
ALTER TABLE usage_history DROP FOREIGN KEY fk_usage_history_org;
ALTER TABLE usage_history DROP FOREIGN KEY fk_usage_history_domain;
ALTER TABLE usage_history DROP FOREIGN KEY fk_usage_history_email_account;

-- ssl_certificates -> domains
ALTER TABLE ssl_certificates DROP FOREIGN KEY fk_ssl_certs_domain;

-- dkim_keys -> domains
ALTER TABLE dkim_keys DROP FOREIGN KEY fk_dkim_keys_domain;

-- ai_transactions -> organizations
ALTER TABLE ai_transactions DROP FOREIGN KEY fk_ai_transactions_org;

-- email_suppressions -> organizations
ALTER TABLE email_suppressions DROP FOREIGN KEY fk_email_suppressions_org;

-- domain_reputation -> domains, organizations
ALTER TABLE domain_reputation DROP FOREIGN KEY fk_domain_reputation_domain;
ALTER TABLE domain_reputation DROP FOREIGN KEY fk_domain_reputation_org;

-- feedback_loops -> organizations
ALTER TABLE feedback_loops DROP FOREIGN KEY fk_feedback_loops_org;

-- analytics_data -> organizations
ALTER TABLE analytics_data DROP FOREIGN KEY fk_analytics_data_org;

-- ip_access_rules -> organizations
ALTER TABLE ip_access_rules DROP FOREIGN KEY fk_ip_rules_org;

-- shared_mailbox_members -> email_accounts (both FKs)
ALTER TABLE shared_mailbox_members DROP FOREIGN KEY fk_shared_mailbox;
ALTER TABLE shared_mailbox_members DROP FOREIGN KEY fk_shared_member;

-- distribution_groups -> organizations
ALTER TABLE distribution_groups DROP FOREIGN KEY fk_group_org;

-- distribution_group_members -> distribution_groups, email_accounts
ALTER TABLE distribution_group_members DROP FOREIGN KEY fk_group_member_group;
ALTER TABLE distribution_group_members DROP FOREIGN KEY fk_group_member_account;

-- transport_rules -> organizations
ALTER TABLE transport_rules DROP FOREIGN KEY fk_transport_org;

-- quarantine -> organizations, transport_rules
ALTER TABLE quarantine DROP FOREIGN KEY fk_quarantine_org;
ALTER TABLE quarantine DROP FOREIGN KEY fk_quarantine_rule;

-- organizations self-ref (005)
ALTER TABLE organizations DROP FOREIGN KEY fk_org_parent;

-- migration_jobs -> organizations
ALTER TABLE migration_jobs DROP FOREIGN KEY fk_migration_org;

-- dlp_policies -> organizations (unnamed FK from 006, use generated name)
-- These may have auto-generated constraint names; drop by looking them up
SET @db_name = DATABASE();

-- dlp_policies FK
SET @fk_name = (
    SELECT CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'dlp_policies'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY' LIMIT 1
);
SET @sql = IF(@fk_name IS NOT NULL, CONCAT('ALTER TABLE dlp_policies DROP FOREIGN KEY `', @fk_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- dlp_violations FKs (org + policy)
SET @fk_name = (
    SELECT CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'dlp_violations'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY' LIMIT 1
);
SET @sql = IF(@fk_name IS NOT NULL, CONCAT('ALTER TABLE dlp_violations DROP FOREIGN KEY `', @fk_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @fk_name = (
    SELECT CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'dlp_violations'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY' LIMIT 1
);
SET @sql = IF(@fk_name IS NOT NULL, CONCAT('ALTER TABLE dlp_violations DROP FOREIGN KEY `', @fk_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- geo_policies FK
SET @fk_name = (
    SELECT CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'geo_policies'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY' LIMIT 1
);
SET @sql = IF(@fk_name IS NOT NULL, CONCAT('ALTER TABLE geo_policies DROP FOREIGN KEY `', @fk_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- oauth_clients FK
ALTER TABLE oauth_clients DROP FOREIGN KEY fk_oauth_client_org;

-- email_templates FK
ALTER TABLE email_templates DROP FOREIGN KEY fk_template_org;

-- email_template_versions FK
ALTER TABLE email_template_versions DROP FOREIGN KEY fk_tmpl_ver_template;

-- email_archive FK
ALTER TABLE email_archive DROP FOREIGN KEY fk_archive_org;

-- retention_policies FK
ALTER TABLE retention_policies DROP FOREIGN KEY fk_retention_org;

-- legal_holds FK
ALTER TABLE legal_holds DROP FOREIGN KEY fk_legal_hold_org;


-- =============================================================================
-- STEP 2: Migrate organizations.id from VARCHAR(100) to CHAR(26)
-- =============================================================================
-- Organizations use VARCHAR(100) user-supplied IDs (e.g. 'acme-corp').
-- We keep existing values (they fit in CHAR(26) if <= 26 chars; longer ones
-- need to be truncated or remapped). For safety we just change the column type.
-- New orgs will use application-generated ULIDs.

ALTER TABLE organizations MODIFY COLUMN id CHAR(26) NOT NULL;
ALTER TABLE organizations MODIFY COLUMN parent_organization_id CHAR(26) NULL;


-- =============================================================================
-- STEP 3: Migrate INT/BIGINT primary keys to CHAR(26)
-- =============================================================================
-- For each table: add new_id, populate with generated ULIDs, then swap.

-- -------------------------
-- 3a. domains
-- -------------------------
ALTER TABLE domains ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE domains SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
-- Update all FK references pointing to domains.id
UPDATE email_accounts ea JOIN domains d ON ea.domain_id = d.id SET ea.domain_id = 0;
-- We need a mapping table approach — use a temp column strategy instead
-- Actually, let's use a different approach: update FK columns via JOIN

-- First, add new FK columns in referencing tables
ALTER TABLE email_accounts ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE aliases ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE dkim_keys ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE ssl_certificates ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE email_tracking ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE tracking_statistics ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE webhook_delivery_logs ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE alerts ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE usage_history ADD COLUMN new_domain_id CHAR(26) NULL;
ALTER TABLE domain_reputation ADD COLUMN new_domain_id CHAR(26) NULL;

-- Populate new FK columns from the mapping
UPDATE email_accounts ea JOIN domains d ON ea.domain_id = d.id SET ea.new_domain_id = d.new_id;
UPDATE aliases a JOIN domains d ON a.domain_id = d.id SET a.new_domain_id = d.new_id;
UPDATE dkim_keys dk JOIN domains d ON dk.domain_id = d.id SET dk.new_domain_id = d.new_id;
UPDATE ssl_certificates sc JOIN domains d ON sc.domain_id = d.id SET sc.new_domain_id = d.new_id;
UPDATE email_tracking et JOIN domains d ON et.domain_id = d.id SET et.new_domain_id = d.new_id;
UPDATE tracking_statistics ts JOIN domains d ON ts.domain_id = d.id SET ts.new_domain_id = d.new_id;
UPDATE webhook_delivery_logs wdl JOIN domains d ON wdl.domain_id = d.id SET wdl.new_domain_id = d.new_id;
UPDATE alerts al JOIN domains d ON al.domain_id = d.id SET al.new_domain_id = d.new_id WHERE al.domain_id IS NOT NULL;
UPDATE usage_history uh JOIN domains d ON uh.domain_id = d.id SET uh.new_domain_id = d.new_id WHERE uh.domain_id IS NOT NULL;
UPDATE domain_reputation dr JOIN domains d ON dr.domain_id = d.id SET dr.new_domain_id = d.new_id;

-- Now swap columns on domains table
ALTER TABLE domains DROP COLUMN id;
ALTER TABLE domains CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE domains ADD PRIMARY KEY (id);

-- Swap domain_id FK columns in referencing tables
ALTER TABLE email_accounts DROP COLUMN domain_id;
ALTER TABLE email_accounts CHANGE COLUMN new_domain_id domain_id CHAR(26) NOT NULL;

ALTER TABLE aliases DROP COLUMN domain_id;
ALTER TABLE aliases CHANGE COLUMN new_domain_id domain_id CHAR(26) NOT NULL;

ALTER TABLE dkim_keys DROP COLUMN domain_id;
ALTER TABLE dkim_keys CHANGE COLUMN new_domain_id domain_id CHAR(26) NOT NULL;

ALTER TABLE ssl_certificates DROP COLUMN domain_id;
ALTER TABLE ssl_certificates CHANGE COLUMN new_domain_id domain_id CHAR(26) NOT NULL;

ALTER TABLE email_tracking DROP COLUMN domain_id;
ALTER TABLE email_tracking CHANGE COLUMN new_domain_id domain_id CHAR(26) NOT NULL;

ALTER TABLE tracking_statistics DROP COLUMN domain_id;
ALTER TABLE tracking_statistics CHANGE COLUMN new_domain_id domain_id CHAR(26) NOT NULL;

ALTER TABLE webhook_delivery_logs DROP COLUMN domain_id;
ALTER TABLE webhook_delivery_logs CHANGE COLUMN new_domain_id domain_id CHAR(26) NULL;

ALTER TABLE alerts DROP COLUMN domain_id;
ALTER TABLE alerts CHANGE COLUMN new_domain_id domain_id CHAR(26) NULL;

ALTER TABLE usage_history DROP COLUMN domain_id;
ALTER TABLE usage_history CHANGE COLUMN new_domain_id domain_id CHAR(26) NULL;

ALTER TABLE domain_reputation DROP COLUMN domain_id;
ALTER TABLE domain_reputation CHANGE COLUMN new_domain_id domain_id CHAR(26) NOT NULL;

-- -------------------------
-- 3b. email_accounts
-- -------------------------
ALTER TABLE email_accounts ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE email_accounts SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;

-- Add new FK columns in referencing tables
ALTER TABLE user_sessions ADD COLUMN new_email_account_id CHAR(26) NULL;
ALTER TABLE alerts ADD COLUMN new_email_account_id CHAR(26) NULL;
ALTER TABLE usage_history ADD COLUMN new_email_account_id CHAR(26) NULL;
ALTER TABLE shared_mailbox_members ADD COLUMN new_shared_mailbox_id CHAR(26) NULL;
ALTER TABLE shared_mailbox_members ADD COLUMN new_email_account_id CHAR(26) NULL;
ALTER TABLE distribution_group_members ADD COLUMN new_email_account_id CHAR(26) NULL;

-- Populate new FK columns
UPDATE user_sessions us JOIN email_accounts ea ON us.email_account_id = ea.id SET us.new_email_account_id = ea.new_id;
UPDATE alerts al JOIN email_accounts ea ON al.email_account_id = ea.id SET al.new_email_account_id = ea.new_id WHERE al.email_account_id IS NOT NULL;
UPDATE usage_history uh JOIN email_accounts ea ON uh.email_account_id = ea.id SET uh.new_email_account_id = ea.new_id WHERE uh.email_account_id IS NOT NULL;
UPDATE shared_mailbox_members smm JOIN email_accounts ea ON smm.shared_mailbox_id = ea.id SET smm.new_shared_mailbox_id = ea.new_id;
UPDATE shared_mailbox_members smm JOIN email_accounts ea ON smm.email_account_id = ea.id SET smm.new_email_account_id = ea.new_id;
UPDATE distribution_group_members dgm JOIN email_accounts ea ON dgm.email_account_id = ea.id SET dgm.new_email_account_id = ea.new_id WHERE dgm.email_account_id IS NOT NULL;

-- Swap PK on email_accounts
ALTER TABLE email_accounts DROP COLUMN id;
ALTER TABLE email_accounts CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE email_accounts ADD PRIMARY KEY (id);

-- Swap FK columns in referencing tables
ALTER TABLE user_sessions DROP COLUMN email_account_id;
ALTER TABLE user_sessions CHANGE COLUMN new_email_account_id email_account_id CHAR(26) NOT NULL;

ALTER TABLE alerts DROP COLUMN email_account_id;
ALTER TABLE alerts CHANGE COLUMN new_email_account_id email_account_id CHAR(26) NULL;

ALTER TABLE usage_history DROP COLUMN email_account_id;
ALTER TABLE usage_history CHANGE COLUMN new_email_account_id email_account_id CHAR(26) NULL;

ALTER TABLE shared_mailbox_members DROP COLUMN shared_mailbox_id;
ALTER TABLE shared_mailbox_members CHANGE COLUMN new_shared_mailbox_id shared_mailbox_id CHAR(26) NOT NULL;

ALTER TABLE shared_mailbox_members DROP COLUMN email_account_id;
ALTER TABLE shared_mailbox_members CHANGE COLUMN new_email_account_id email_account_id CHAR(26) NOT NULL;

ALTER TABLE distribution_group_members DROP COLUMN email_account_id;
ALTER TABLE distribution_group_members CHANGE COLUMN new_email_account_id email_account_id CHAR(26) NULL;

-- -------------------------
-- 3c. aliases
-- -------------------------
ALTER TABLE aliases ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE aliases SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE aliases DROP COLUMN id;
ALTER TABLE aliases CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE aliases ADD PRIMARY KEY (id);

-- -------------------------
-- 3d. api_keys
-- -------------------------
ALTER TABLE api_keys ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE api_keys SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;

-- api_rate_limits may reference api_keys.id
ALTER TABLE api_rate_limits MODIFY COLUMN api_key_id CHAR(26) NULL;

-- Update api_rate_limits FK values
UPDATE api_rate_limits arl JOIN api_keys ak ON arl.api_key_id = ak.id SET arl.api_key_id = ak.new_id WHERE arl.api_key_id IS NOT NULL;

ALTER TABLE api_keys DROP COLUMN id;
ALTER TABLE api_keys CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE api_keys ADD PRIMARY KEY (id);

-- -------------------------
-- 3e. dkim_keys
-- -------------------------
ALTER TABLE dkim_keys ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE dkim_keys SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE dkim_keys DROP COLUMN id;
ALTER TABLE dkim_keys CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE dkim_keys ADD PRIMARY KEY (id);

-- -------------------------
-- 3f. email_tracking
-- -------------------------
ALTER TABLE email_tracking ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE email_tracking SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE email_tracking DROP COLUMN id;
ALTER TABLE email_tracking CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE email_tracking ADD PRIMARY KEY (id);

-- -------------------------
-- 3g. mail_logs (partitioned — need to handle carefully)
-- -------------------------
-- mail_logs may be partitioned. We need to remove partitioning first, alter, then re-partition.
ALTER TABLE mail_logs REMOVE PARTITIONING;

ALTER TABLE mail_logs ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE mail_logs SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE mail_logs DROP COLUMN id;
ALTER TABLE mail_logs CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE mail_logs ADD PRIMARY KEY (id);

-- -------------------------
-- 3h. audit_logs
-- -------------------------
ALTER TABLE audit_logs ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE audit_logs SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE audit_logs DROP COLUMN id;
ALTER TABLE audit_logs CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE audit_logs ADD PRIMARY KEY (id);

-- -------------------------
-- 3i. webhook_delivery_logs
-- -------------------------
ALTER TABLE webhook_delivery_logs ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE webhook_delivery_logs SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE webhook_delivery_logs DROP COLUMN id;
ALTER TABLE webhook_delivery_logs CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE webhook_delivery_logs ADD PRIMARY KEY (id);

-- -------------------------
-- 3j. ssl_certificates
-- -------------------------
ALTER TABLE ssl_certificates ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE ssl_certificates SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE ssl_certificates DROP COLUMN id;
ALTER TABLE ssl_certificates CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE ssl_certificates ADD PRIMARY KEY (id);

-- -------------------------
-- 3k. transport_rules
-- -------------------------
ALTER TABLE transport_rules ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE transport_rules SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;

-- quarantine.rule_id references transport_rules.id
ALTER TABLE quarantine ADD COLUMN new_rule_id CHAR(26) NULL;
UPDATE quarantine q JOIN transport_rules tr ON q.rule_id = tr.id SET q.new_rule_id = tr.new_id WHERE q.rule_id IS NOT NULL;
ALTER TABLE quarantine DROP COLUMN rule_id;
ALTER TABLE quarantine CHANGE COLUMN new_rule_id rule_id CHAR(26) NULL;

ALTER TABLE transport_rules DROP COLUMN id;
ALTER TABLE transport_rules CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE transport_rules ADD PRIMARY KEY (id);

-- -------------------------
-- 3l. quarantine
-- -------------------------
ALTER TABLE quarantine ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE quarantine SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE quarantine DROP COLUMN id;
ALTER TABLE quarantine CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE quarantine ADD PRIMARY KEY (id);

-- -------------------------
-- 3m. health_checks
-- -------------------------
ALTER TABLE health_checks ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE health_checks SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE health_checks DROP COLUMN id;
ALTER TABLE health_checks CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE health_checks ADD PRIMARY KEY (id);

-- -------------------------
-- 3n. service_metrics
-- -------------------------
ALTER TABLE service_metrics ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE service_metrics SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE service_metrics DROP COLUMN id;
ALTER TABLE service_metrics CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE service_metrics ADD PRIMARY KEY (id);

-- -------------------------
-- 3o. url_clicks
-- -------------------------
ALTER TABLE url_clicks ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE url_clicks SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE url_clicks DROP COLUMN id;
ALTER TABLE url_clicks CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE url_clicks ADD PRIMARY KEY (id);

-- -------------------------
-- 3p. tracking_statistics
-- -------------------------
ALTER TABLE tracking_statistics ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE tracking_statistics SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE tracking_statistics DROP COLUMN id;
ALTER TABLE tracking_statistics CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE tracking_statistics ADD PRIMARY KEY (id);

-- -------------------------
-- 3q. email_suppressions
-- -------------------------
ALTER TABLE email_suppressions ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE email_suppressions SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE email_suppressions DROP COLUMN id;
ALTER TABLE email_suppressions CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE email_suppressions ADD PRIMARY KEY (id);

-- -------------------------
-- 3r. user_sessions — PK is VARCHAR(255), change to CHAR(26)
-- -------------------------
ALTER TABLE user_sessions MODIFY COLUMN id CHAR(26) NOT NULL;

-- -------------------------
-- 3s. migration_jobs
-- -------------------------
ALTER TABLE migration_jobs ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE migration_jobs SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE migration_jobs DROP COLUMN id;
ALTER TABLE migration_jobs CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE migration_jobs ADD PRIMARY KEY (id);

-- -------------------------
-- 3t. webhook_urls
-- -------------------------
ALTER TABLE webhook_urls ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE webhook_urls SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;

-- webhook_delivery_logs.webhook_url_id references webhook_urls.id
ALTER TABLE webhook_delivery_logs ADD COLUMN new_webhook_url_id CHAR(26) NULL;
UPDATE webhook_delivery_logs wdl JOIN webhook_urls wu ON wdl.webhook_url_id = wu.id SET wdl.new_webhook_url_id = wu.new_id WHERE wdl.webhook_url_id IS NOT NULL;
ALTER TABLE webhook_delivery_logs DROP COLUMN webhook_url_id;
ALTER TABLE webhook_delivery_logs CHANGE COLUMN new_webhook_url_id webhook_url_id CHAR(26) NULL;

ALTER TABLE webhook_urls DROP COLUMN id;
ALTER TABLE webhook_urls CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE webhook_urls ADD PRIMARY KEY (id);

-- -------------------------
-- 3u. Additional tables with INT PKs that need ULID migration
-- -------------------------

-- mail_queue (partitioned)
ALTER TABLE mail_queue REMOVE PARTITIONING;
ALTER TABLE mail_queue ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE mail_queue SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE mail_queue DROP COLUMN id;
ALTER TABLE mail_queue CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE mail_queue ADD PRIMARY KEY (id);

-- alerts
ALTER TABLE alerts ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE alerts SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE alerts DROP COLUMN id;
ALTER TABLE alerts CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE alerts ADD PRIMARY KEY (id);

-- usage_history
ALTER TABLE usage_history ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE usage_history SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE usage_history DROP COLUMN id;
ALTER TABLE usage_history CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE usage_history ADD PRIMARY KEY (id);

-- ai_transactions
ALTER TABLE ai_transactions ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE ai_transactions SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE ai_transactions DROP COLUMN id;
ALTER TABLE ai_transactions CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE ai_transactions ADD PRIMARY KEY (id);

-- domain_reputation
ALTER TABLE domain_reputation ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE domain_reputation SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE domain_reputation DROP COLUMN id;
ALTER TABLE domain_reputation CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE domain_reputation ADD PRIMARY KEY (id);

-- feedback_loops
ALTER TABLE feedback_loops ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE feedback_loops SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE feedback_loops DROP COLUMN id;
ALTER TABLE feedback_loops CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE feedback_loops ADD PRIMARY KEY (id);

-- analytics_data
ALTER TABLE analytics_data ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE analytics_data SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE analytics_data DROP COLUMN id;
ALTER TABLE analytics_data CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE analytics_data ADD PRIMARY KEY (id);

-- ip_access_rules
ALTER TABLE ip_access_rules ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE ip_access_rules SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE ip_access_rules DROP COLUMN id;
ALTER TABLE ip_access_rules CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE ip_access_rules ADD PRIMARY KEY (id);

-- failed_auth_attempts
ALTER TABLE failed_auth_attempts ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE failed_auth_attempts SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE failed_auth_attempts DROP COLUMN id;
ALTER TABLE failed_auth_attempts CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE failed_auth_attempts ADD PRIMARY KEY (id);

-- ip_reputation
ALTER TABLE ip_reputation ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE ip_reputation SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE ip_reputation DROP COLUMN id;
ALTER TABLE ip_reputation CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE ip_reputation ADD PRIMARY KEY (id);

-- shared_mailbox_members
ALTER TABLE shared_mailbox_members ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE shared_mailbox_members SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE shared_mailbox_members DROP COLUMN id;
ALTER TABLE shared_mailbox_members CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE shared_mailbox_members ADD PRIMARY KEY (id);

-- distribution_groups
ALTER TABLE distribution_groups ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE distribution_groups SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;

-- distribution_group_members.group_id references distribution_groups.id
ALTER TABLE distribution_group_members ADD COLUMN new_group_id CHAR(26) NULL;
UPDATE distribution_group_members dgm JOIN distribution_groups dg ON dgm.group_id = dg.id SET dgm.new_group_id = dg.new_id;
ALTER TABLE distribution_group_members DROP COLUMN group_id;
ALTER TABLE distribution_group_members CHANGE COLUMN new_group_id group_id CHAR(26) NOT NULL;

ALTER TABLE distribution_groups DROP COLUMN id;
ALTER TABLE distribution_groups CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE distribution_groups ADD PRIMARY KEY (id);

-- distribution_group_members
ALTER TABLE distribution_group_members ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE distribution_group_members SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE distribution_group_members DROP COLUMN id;
ALTER TABLE distribution_group_members CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE distribution_group_members ADD PRIMARY KEY (id);

-- dlp_policies
ALTER TABLE dlp_policies ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE dlp_policies SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;

-- dlp_violations.policy_id references dlp_policies.id
ALTER TABLE dlp_violations MODIFY COLUMN policy_id CHAR(26) NOT NULL;
UPDATE dlp_violations dv JOIN dlp_policies dp ON dv.policy_id = dp.id SET dv.policy_id = dp.new_id;

ALTER TABLE dlp_policies DROP COLUMN id;
ALTER TABLE dlp_policies CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE dlp_policies ADD PRIMARY KEY (id);

-- dlp_violations
ALTER TABLE dlp_violations ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE dlp_violations SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE dlp_violations DROP COLUMN id;
ALTER TABLE dlp_violations CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE dlp_violations ADD PRIMARY KEY (id);

-- totp_secrets
ALTER TABLE totp_secrets ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE totp_secrets SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE totp_secrets DROP COLUMN id;
ALTER TABLE totp_secrets CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE totp_secrets ADD PRIMARY KEY (id);

-- geo_policies
ALTER TABLE geo_policies ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE geo_policies SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE geo_policies DROP COLUMN id;
ALTER TABLE geo_policies CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE geo_policies ADD PRIMARY KEY (id);

-- consent_records
ALTER TABLE consent_records ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE consent_records SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE consent_records DROP COLUMN id;
ALTER TABLE consent_records CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE consent_records ADD PRIMARY KEY (id);

-- data_export_requests
ALTER TABLE data_export_requests ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE data_export_requests SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE data_export_requests DROP COLUMN id;
ALTER TABLE data_export_requests CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE data_export_requests ADD PRIMARY KEY (id);

-- data_erasure_requests
ALTER TABLE data_erasure_requests ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE data_erasure_requests SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE data_erasure_requests DROP COLUMN id;
ALTER TABLE data_erasure_requests CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE data_erasure_requests ADD PRIMARY KEY (id);

-- jmap_states
ALTER TABLE jmap_states ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE jmap_states SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE jmap_states DROP COLUMN id;
ALTER TABLE jmap_states CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE jmap_states ADD PRIMARY KEY (id);

-- kafka_dead_letters
ALTER TABLE kafka_dead_letters ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE kafka_dead_letters SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE kafka_dead_letters DROP COLUMN id;
ALTER TABLE kafka_dead_letters CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE kafka_dead_letters ADD PRIMARY KEY (id);

-- migration_errors
ALTER TABLE migration_errors ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE migration_errors SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE migration_errors DROP COLUMN id;
ALTER TABLE migration_errors CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE migration_errors ADD PRIMARY KEY (id);

-- pgp_keys
ALTER TABLE pgp_keys ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE pgp_keys SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE pgp_keys DROP COLUMN id;
ALTER TABLE pgp_keys CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE pgp_keys ADD PRIMARY KEY (id);

-- smime_certs
ALTER TABLE smime_certs ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE smime_certs SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE smime_certs DROP COLUMN id;
ALTER TABLE smime_certs CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE smime_certs ADD PRIMARY KEY (id);

-- oauth_clients
ALTER TABLE oauth_clients ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE oauth_clients SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE oauth_clients DROP COLUMN id;
ALTER TABLE oauth_clients CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE oauth_clients ADD PRIMARY KEY (id);

-- oauth_grants
ALTER TABLE oauth_grants ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE oauth_grants SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE oauth_grants DROP COLUMN id;
ALTER TABLE oauth_grants CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE oauth_grants ADD PRIMARY KEY (id);

-- url_blocklist
ALTER TABLE url_blocklist ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE url_blocklist SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE url_blocklist DROP COLUMN id;
ALTER TABLE url_blocklist CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE url_blocklist ADD PRIMARY KEY (id);

-- email_templates
ALTER TABLE email_templates ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE email_templates SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;

-- email_template_versions.template_id references email_templates.id
ALTER TABLE email_template_versions MODIFY COLUMN template_id CHAR(26) NOT NULL;
UPDATE email_template_versions etv JOIN email_templates et ON etv.template_id = et.id SET etv.template_id = et.new_id;

-- template_render_log.template_id references email_templates.id
ALTER TABLE template_render_log MODIFY COLUMN template_id CHAR(26) NULL;
UPDATE template_render_log trl JOIN email_templates et ON trl.template_id = et.id SET trl.template_id = et.new_id WHERE trl.template_id IS NOT NULL;

ALTER TABLE email_templates DROP COLUMN id;
ALTER TABLE email_templates CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE email_templates ADD PRIMARY KEY (id);

-- email_template_versions
ALTER TABLE email_template_versions ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE email_template_versions SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE email_template_versions DROP COLUMN id;
ALTER TABLE email_template_versions CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE email_template_versions ADD PRIMARY KEY (id);

-- template_render_log
ALTER TABLE template_render_log ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE template_render_log SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE template_render_log DROP COLUMN id;
ALTER TABLE template_render_log CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE template_render_log ADD PRIMARY KEY (id);

-- email_archive
ALTER TABLE email_archive ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE email_archive SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE email_archive DROP COLUMN id;
ALTER TABLE email_archive CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE email_archive ADD PRIMARY KEY (id);

-- retention_policies
ALTER TABLE retention_policies ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE retention_policies SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE retention_policies DROP COLUMN id;
ALTER TABLE retention_policies CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE retention_policies ADD PRIMARY KEY (id);

-- legal_holds
ALTER TABLE legal_holds ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE legal_holds SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE legal_holds DROP COLUMN id;
ALTER TABLE legal_holds CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE legal_holds ADD PRIMARY KEY (id);

-- storage_usage
ALTER TABLE storage_usage ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE storage_usage SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE storage_usage DROP COLUMN id;
ALTER TABLE storage_usage CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE storage_usage ADD PRIMARY KEY (id);

-- storage_alerts
ALTER TABLE storage_alerts ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE storage_alerts SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE storage_alerts DROP COLUMN id;
ALTER TABLE storage_alerts CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE storage_alerts ADD PRIMARY KEY (id);

-- rate_limit_configs
ALTER TABLE rate_limit_configs ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE rate_limit_configs SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE rate_limit_configs DROP COLUMN id;
ALTER TABLE rate_limit_configs CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE rate_limit_configs ADD PRIMARY KEY (id);

-- rate_limit_alerts
ALTER TABLE rate_limit_alerts ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE rate_limit_alerts SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE rate_limit_alerts DROP COLUMN id;
ALTER TABLE rate_limit_alerts CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE rate_limit_alerts ADD PRIMARY KEY (id);

-- queue_statistics
ALTER TABLE queue_statistics ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE queue_statistics SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE queue_statistics DROP COLUMN id;
ALTER TABLE queue_statistics CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE queue_statistics ADD PRIMARY KEY (id);

-- bounce_events
ALTER TABLE bounce_events ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE bounce_events SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE bounce_events DROP COLUMN id;
ALTER TABLE bounce_events CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE bounce_events ADD PRIMARY KEY (id);

-- user_logins
ALTER TABLE user_logins ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE user_logins SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE user_logins DROP COLUMN id;
ALTER TABLE user_logins CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE user_logins ADD PRIMARY KEY (id);

-- webhook_dead_letters
ALTER TABLE webhook_dead_letters ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE webhook_dead_letters SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE webhook_dead_letters DROP COLUMN id;
ALTER TABLE webhook_dead_letters CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE webhook_dead_letters ADD PRIMARY KEY (id);

-- backup_history
ALTER TABLE backup_history ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE backup_history SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE backup_history DROP COLUMN id;
ALTER TABLE backup_history CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE backup_history ADD PRIMARY KEY (id);

-- api_rate_limits
ALTER TABLE api_rate_limits ADD COLUMN new_id CHAR(26) NULL AFTER id;
UPDATE api_rate_limits SET new_id = generate_ulid_backfill() WHERE new_id IS NULL;
ALTER TABLE api_rate_limits DROP COLUMN id;
ALTER TABLE api_rate_limits CHANGE COLUMN new_id id CHAR(26) NOT NULL;
ALTER TABLE api_rate_limits ADD PRIMARY KEY (id);


-- =============================================================================
-- STEP 4: Alter remaining FK columns to CHAR(26)
-- =============================================================================
-- All organization_id FK columns need to be CHAR(26)

ALTER TABLE domains MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE email_accounts MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE aliases MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE mail_queue MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE mail_logs MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE email_tracking MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE tracking_statistics MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE api_keys MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE webhook_urls MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE webhook_delivery_logs MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE alerts MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE usage_history MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE ai_transactions MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE email_suppressions MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE domain_reputation MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE feedback_loops MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE analytics_data MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE ip_access_rules MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE distribution_groups MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE transport_rules MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE quarantine MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE migration_jobs MODIFY COLUMN org_id CHAR(26) NULL;
ALTER TABLE dlp_policies MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE dlp_violations MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE geo_policies MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE oauth_clients MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE email_templates MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE template_render_log MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE email_archive MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE retention_policies MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE legal_holds MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE storage_usage MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE storage_alerts MODIFY COLUMN organization_id CHAR(26) NOT NULL;
ALTER TABLE rate_limit_configs MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE rate_limit_alerts MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE bounce_events MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE webhook_dead_letters MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE api_rate_limits MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE url_blocklist MODIFY COLUMN organization_id CHAR(26) NULL;
ALTER TABLE url_clicks MODIFY COLUMN organization_id CHAR(26) NULL;


-- =============================================================================
-- STEP 5: Re-add ALL foreign key constraints
-- =============================================================================

-- organizations self-reference
ALTER TABLE organizations ADD CONSTRAINT fk_org_parent
    FOREIGN KEY (parent_organization_id) REFERENCES organizations(id) ON DELETE SET NULL;

-- domains -> organizations
ALTER TABLE domains ADD CONSTRAINT fk_domains_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- email_accounts -> domains, organizations
ALTER TABLE email_accounts ADD CONSTRAINT fk_email_accounts_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);
ALTER TABLE email_accounts ADD CONSTRAINT fk_email_accounts_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- aliases -> domains, organizations
ALTER TABLE aliases ADD CONSTRAINT fk_aliases_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);
ALTER TABLE aliases ADD CONSTRAINT fk_aliases_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- user_sessions -> email_accounts
ALTER TABLE user_sessions ADD CONSTRAINT fk_sessions_email_account
    FOREIGN KEY (email_account_id) REFERENCES email_accounts(id);

-- mail_queue -> organizations
ALTER TABLE mail_queue ADD CONSTRAINT fk_mail_queue_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- mail_logs -> organizations
ALTER TABLE mail_logs ADD CONSTRAINT fk_mail_logs_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- email_tracking -> organizations, domains
ALTER TABLE email_tracking ADD CONSTRAINT fk_email_tracking_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE email_tracking ADD CONSTRAINT fk_email_tracking_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);

-- tracking_statistics -> organizations, domains
ALTER TABLE tracking_statistics ADD CONSTRAINT fk_tracking_stats_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE tracking_statistics ADD CONSTRAINT fk_tracking_stats_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);

-- api_keys -> organizations
ALTER TABLE api_keys ADD CONSTRAINT fk_api_keys_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- webhook_urls -> organizations
ALTER TABLE webhook_urls ADD CONSTRAINT fk_webhook_urls_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- webhook_delivery_logs -> webhook_urls, organizations, domains
ALTER TABLE webhook_delivery_logs ADD CONSTRAINT fk_webhook_delivery_url
    FOREIGN KEY (webhook_url_id) REFERENCES webhook_urls(id);
ALTER TABLE webhook_delivery_logs ADD CONSTRAINT fk_webhook_delivery_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE webhook_delivery_logs ADD CONSTRAINT fk_webhook_delivery_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);

-- alerts -> organizations, domains, email_accounts
ALTER TABLE alerts ADD CONSTRAINT fk_alerts_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE alerts ADD CONSTRAINT fk_alerts_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);
ALTER TABLE alerts ADD CONSTRAINT fk_alerts_email_account
    FOREIGN KEY (email_account_id) REFERENCES email_accounts(id);

-- usage_history -> organizations, domains, email_accounts
ALTER TABLE usage_history ADD CONSTRAINT fk_usage_history_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE usage_history ADD CONSTRAINT fk_usage_history_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);
ALTER TABLE usage_history ADD CONSTRAINT fk_usage_history_email_account
    FOREIGN KEY (email_account_id) REFERENCES email_accounts(id);

-- ssl_certificates -> domains
ALTER TABLE ssl_certificates ADD CONSTRAINT fk_ssl_certs_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);

-- dkim_keys -> domains
ALTER TABLE dkim_keys ADD CONSTRAINT fk_dkim_keys_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);

-- ai_transactions -> organizations
ALTER TABLE ai_transactions ADD CONSTRAINT fk_ai_transactions_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- email_suppressions -> organizations
ALTER TABLE email_suppressions ADD CONSTRAINT fk_email_suppressions_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- domain_reputation -> domains, organizations
ALTER TABLE domain_reputation ADD CONSTRAINT fk_domain_reputation_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id);
ALTER TABLE domain_reputation ADD CONSTRAINT fk_domain_reputation_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- feedback_loops -> organizations
ALTER TABLE feedback_loops ADD CONSTRAINT fk_feedback_loops_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- analytics_data -> organizations
ALTER TABLE analytics_data ADD CONSTRAINT fk_analytics_data_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- ip_access_rules -> organizations
ALTER TABLE ip_access_rules ADD CONSTRAINT fk_ip_rules_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- shared_mailbox_members -> email_accounts (both)
ALTER TABLE shared_mailbox_members ADD CONSTRAINT fk_shared_mailbox
    FOREIGN KEY (shared_mailbox_id) REFERENCES email_accounts(id) ON DELETE CASCADE;
ALTER TABLE shared_mailbox_members ADD CONSTRAINT fk_shared_member
    FOREIGN KEY (email_account_id) REFERENCES email_accounts(id) ON DELETE CASCADE;

-- distribution_groups -> organizations
ALTER TABLE distribution_groups ADD CONSTRAINT fk_group_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- distribution_group_members -> distribution_groups, email_accounts
ALTER TABLE distribution_group_members ADD CONSTRAINT fk_group_member_group
    FOREIGN KEY (group_id) REFERENCES distribution_groups(id) ON DELETE CASCADE;
ALTER TABLE distribution_group_members ADD CONSTRAINT fk_group_member_account
    FOREIGN KEY (email_account_id) REFERENCES email_accounts(id) ON DELETE SET NULL;

-- transport_rules -> organizations
ALTER TABLE transport_rules ADD CONSTRAINT fk_transport_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- quarantine -> organizations, transport_rules
ALTER TABLE quarantine ADD CONSTRAINT fk_quarantine_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE quarantine ADD CONSTRAINT fk_quarantine_rule
    FOREIGN KEY (rule_id) REFERENCES transport_rules(id) ON DELETE SET NULL;

-- migration_jobs -> organizations
ALTER TABLE migration_jobs ADD CONSTRAINT fk_migration_org
    FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;

-- dlp_policies -> organizations
ALTER TABLE dlp_policies ADD CONSTRAINT fk_dlp_policies_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- dlp_violations -> organizations, dlp_policies
ALTER TABLE dlp_violations ADD CONSTRAINT fk_dlp_violations_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE dlp_violations ADD CONSTRAINT fk_dlp_violations_policy
    FOREIGN KEY (policy_id) REFERENCES dlp_policies(id) ON DELETE CASCADE;

-- geo_policies -> organizations
ALTER TABLE geo_policies ADD CONSTRAINT fk_geo_policies_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- oauth_clients -> organizations
ALTER TABLE oauth_clients ADD CONSTRAINT fk_oauth_client_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- email_templates -> organizations
ALTER TABLE email_templates ADD CONSTRAINT fk_template_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- email_template_versions -> email_templates
ALTER TABLE email_template_versions ADD CONSTRAINT fk_tmpl_ver_template
    FOREIGN KEY (template_id) REFERENCES email_templates(id) ON DELETE CASCADE;

-- email_archive -> organizations
ALTER TABLE email_archive ADD CONSTRAINT fk_archive_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- retention_policies -> organizations
ALTER TABLE retention_policies ADD CONSTRAINT fk_retention_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- legal_holds -> organizations
ALTER TABLE legal_holds ADD CONSTRAINT fk_legal_hold_org
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

-- migration_errors -> migration_jobs (FK on job_id VARCHAR column, not the PK)
-- This FK references migration_jobs.job_id (VARCHAR), not the new ULID PK,
-- so it remains unchanged.


-- =============================================================================
-- STEP 6: Recreate the audit_log compatibility view
-- =============================================================================
-- The view was created in migration 008 and references audit_logs columns.
-- Since we changed the id type, recreate it.

CREATE OR REPLACE VIEW audit_log AS
    SELECT
        id,
        event_type  AS action,
        user_email,
        performed_by,
        client_ip   AS ip_address,
        details,
        created_at
    FROM audit_logs;


-- =============================================================================
-- STEP 7: Clean up helper function
-- =============================================================================

DROP FUNCTION IF EXISTS generate_ulid_backfill;


-- =============================================================================
-- STEP 8: Update Alembic version
-- =============================================================================

UPDATE alembic_version SET version_num = '009_ulid_primary_keys'
WHERE version_num = '008_missing_tables';

INSERT INTO alembic_version (version_num)
SELECT '009_ulid_primary_keys'
WHERE NOT EXISTS (
    SELECT 1 FROM alembic_version WHERE version_num = '009_ulid_primary_keys'
);
